function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>t.classList.remove('show'),2300)}
function showScreen(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.navBtn').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));scrollTo({top:0,behavior:'smooth'});if(id==='route')renderRoute();if(id==='places')renderPlaces();if(id==='plan'){renderShopping();renderChecklist();renderBudget()}}
$$('.navBtn').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.screen)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.go)));
function zonedParts(){const f=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false});const parts=Object.fromEntries(f.formatToParts(new Date()).map(p=>[p.type,p.value]));return {weekday:parts.weekday,hour:Number(parts.hour)%24,minute:Number(parts.minute)}}
function bridgeStatuses(){const {weekday,hour,minute}=zonedParts(),mins=hour*60+minute,weekend=['Sat','Sun'].includes(weekday);return [
  {id:'hidalgo',name:'Hidalgo',open:true,status:'Abierto',detail:'24 h · opción flexible',rank:2},
  {id:'anzalduas',name:'Anzaldúas',open:mins>=360&&mins<1320,status:mins>=360&&mins<1320?'Abierto':'Cerrado',detail:'06:00–22:00',rank:1},
  {id:'pharrbridge',name:'Pharr',open:weekend?((mins>=360&&mins<480)||(mins>=960&&mins<1435)):((mins>=360&&mins<480)||(mins>=960&&mins<1080)),status:'Ventana',detail:weekend?'06–08 y 16–23:55':'06–08 y 16–18',rank:3}
]}
function renderBridges(){const bs=bridgeStatuses();const recommended=bs.find(b=>b.id==='anzalduas'&&b.open)||bs[0];$('#bridgeList').innerHTML=bs.map(b=>`<div class="bridge ${b.id===recommended.id?'openRecommended':''}"><div class="bridgeIcon">🌉</div><div><b>${b.name}</b><small>${b.detail}</small></div><span class="openState ${b.open?'open':'closed'}">${b.open?'ABIERTO':'CERRADO'}</span></div>`).join('');$('#bestBridge').textContent=`🚗 ${recommended.name} disponible`;$('#bestBridgeSub').textContent=recommended.id==='anzalduas'?'Comparar fila con Hidalgo':'Hidalgo permanece 24 h';const db=$('#dashBridge');if(db)db.textContent=recommended.name}
function updateClock(){try{$('#mcallenClock').textContent=new Intl.DateTimeFormat('es-MX',{timeZone:'America/Chicago',hour:'2-digit',minute:'2-digit'}).format(new Date())}catch{$('#mcallenClock').textContent='Hora central'}renderBridges()}
$('#refreshBridge').addEventListener('click',()=>{updateClock();toast('Horarios recalculados')});updateClock();setInterval(updateClock,60000);
function currentRoute(day=state.day){const settings=store.get('mcallen.settings',{days:2,pace:'family',hotel:'comfort'});let ids=[...(routes[day]||[])];if(settings.pace==='fast')ids=ids.filter(id=>!['imas','quinta'].includes(id));if(settings.hotel==='home2')ids=ids.map(id=>id==='comfort'?'home2':id);else ids=ids.map(id=>id==='home2'?'comfort':id);if(Number(settings.days)===1&&day===1)ids=ids.filter(id=>!['ihopSouth','quinta'].includes(id));return [...new Set(ids)]}
function renderRoute(){const done=store.get('mcallen.visited',[]),ids=currentRoute();$('#routeStops').innerHTML=ids.map((id,i)=>{const p=spots.find(x=>x.id===id);return `<div class="routeStop ${done.includes(id)?'done':''}" data-id="${id}"><div class="stopNo">${i+1}</div><div><b>${p.icon} ${p.name}</b><small>${p.desc}</small><div class="actions"><a class="btn" href="${mapUrl(p.query)}" target="_blank" rel="noopener">Maps</a><button class="btn visitBtn">${done.includes(id)?'Desmarcar':'Ya fuimos'}</button></div></div></div>`}).join('');$$('.visitBtn','#routeStops').forEach(b=>b.addEventListener('click',()=>toggleVisited(b.closest('.routeStop').dataset.id)));$('#navCurrentDay').onclick=()=>open(directionsUrl(ids),'_blank','noopener');renderProgress()}
$$('#dayChips .chip').forEach(b=>b.addEventListener('click',()=>{state.day=Number(b.dataset.day);$$('#dayChips .chip').forEach(x=>x.classList.toggle('active',x===b));renderRoute()}));
function toggleVisited(id){let d=store.get('mcallen.visited',[]);d=d.includes(id)?d.filter(x=>x!==id):[...d,id];store.set('mcallen.visited',d);renderRoute();renderPlaces();renderProgress()}
