function renderProgress(){const all=[...new Set([...currentRoute(1),...currentRoute(2)])],done=store.get('mcallen.visited',[]).filter(id=>all.includes(id)),pct=Math.round(done.length/all.length*100)||0;$('#homeProgress').textContent=`${pct}%`;$('#homeProgressBar').style.width=`${pct}%`;const dp=$('#dashProgressRing'),dt=$('#dashProgressText');if(dp)dp.style.setProperty('--meter',`${pct}%`);if(dt)dt.textContent=`${pct}%`;const checks=store.get('mcallen.checks',{}),checkPct=Math.round(Object.values(checks).filter(Boolean).length/defaultChecklist.length*100)||0,overall=Math.round((pct+checkPct)/2);$('#tripReady').textContent=`${overall}%`;$('#tripReadyBar').style.width=`${overall}%`;const rr=$('#readyRing');if(rr)rr.style.setProperty('--ring',`${overall}%`);$('#tripReadyText').textContent=overall<40?'Todavía hay detalles importantes por preparar.':overall<80?'Va tomando forma; ya no parece expedición improvisada.':'Listos para cruzar con dignidad logística.'}
$('#navDay1').addEventListener('click',()=>open(directionsUrl(currentRoute(1)),'_blank','noopener'));
const cats=['Todos','Compras','Comida','Hotel','Niños','Esenciales','Cruce','Extra','Agregados'];$('#placeFilters').innerHTML=cats.map(c=>`<button class="chip ${c==='Todos'?'active':''}" data-cat="${c}">${c}</button>`).join('');$$('#placeFilters .chip').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.cat;$$('#placeFilters .chip').forEach(x=>x.classList.toggle('active',x===b));renderPlaces()}));$('#placeSearch').addEventListener('input',renderPlaces);
function distanceLabel(p){if(!state.userLocation||!Number.isFinite(p.lat)||!Number.isFinite(p.lon))return '';const km=haversineKm(state.userLocation.lat,state.userLocation.lon,p.lat,p.lon);return `<span class="tag gold">${formatDistance(km)}</span>`}
function renderPlaces(){const q=($('#placeSearch').value||'').toLowerCase(),done=store.get('mcallen.visited',[]);const list=allSpots().filter(p=>((state.category==='Todos')||(state.category==='Agregados'&&p.custom)||(p.cat===state.category))&&`${p.name} ${p.zone||''} ${p.desc||''} ${p.address||''}`.toLowerCase().includes(q));$('#placeGrid').innerHTML=list.length?list.map(p=>`<article class="card place ${done.includes(p.id)?'done':''}" data-id="${p.id}" data-cat="${p.cat}"><div class="placeIcon">${p.icon||'📍'}</div><div><span class="tag">${escapeHtml(p.cat||'Lugar')}</span><span class="tag gray">${escapeHtml(p.zone||'McAllen')}</span>${distanceLabel(p)}<h3>${escapeHtml(p.name)}</h3><address>${escapeHtml(p.address||p.query)}</address>${p.hours?`<p><strong>Horario:</strong> ${escapeHtml(p.hours)}</p>`:''}<p>${escapeHtml(p.desc||'Lugar guardado desde la búsqueda.')}</p><div class="actions"><a class="btn primary" href="${mapUrl(p.query)}" target="_blank" rel="noopener">Google Maps</a><a class="btn" href="${wazeUrl(p.query)}" target="_blank" rel="noopener">Waze</a><button class="btn placeVisit">${done.includes(p.id)?'Desmarcar':'Ya fuimos'}</button><button class="btn addDay" data-day="1">＋ Día 1</button><button class="btn addDay" data-day="2">＋ Día 2</button>${p.custom?'<button class="btn deletePlace">Eliminar</button>':''}</div></div></article>`).join(''):'<article class="card empty">No encontré coincidencias locales. Usa “Buscar en McAllen” para consultar lugares en línea.</article>';$$('.placeVisit','#placeGrid').forEach(b=>b.addEventListener('click',()=>toggleVisited(b.closest('.place').dataset.id)));$$('.addDay','#placeGrid').forEach(b=>b.addEventListener('click',()=>addPlaceToDay(b.closest('.place').dataset.id,Number(b.dataset.day))));$$('.deletePlace','#placeGrid').forEach(b=>b.addEventListener('click',()=>deleteCustomPlace(b.closest('.place').dataset.id)))}
$$('[data-quick]').forEach(b=>b.addEventListener('click',()=>{const q=b.dataset.quick;if(q==='shopping'){state.category='Compras';showScreen('places');$$('#placeFilters .chip').forEach(x=>x.classList.toggle('active',x.dataset.cat==='Compras'));renderPlaces()}else if(q==='food'){state.category='Comida';showScreen('places');$$('#placeFilters .chip').forEach(x=>x.classList.toggle('active',x.dataset.cat==='Comida'));renderPlaces()}else if(q==='budget')showScreen('plan');else{state.category='Niños';showScreen('places');$$('#placeFilters .chip').forEach(x=>x.classList.toggle('active',x.dataset.cat==='Niños'));renderPlaces()}}));
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0)}
function renderBudget(){const b=store.get('mcallen.budget',{total:'',spent:''});$('#budgetTotal').value=b.total;$('#budgetSpent').value=b.spent;const total=Number(b.total)||0,spent=Number(b.spent)||0,rem=total-spent,pct=total?Math.max(0,Math.min(100,Math.round(rem/total*100))):0;$('#budgetRemaining').textContent=money(rem);const msg=!b.total?'Define un presupuesto para comenzar.':rem<0?`Se pasaron ${money(Math.abs(rem))}. La tarjeta ya está sudando.`:rem<total*.2?'Queda menos del 20%. Momento de distinguir deseo de necesidad.':'Presupuesto bajo control.';$('#budgetMessage').textContent=msg;const ring=$('#budgetRing'),ringText=$('#budgetRingText'),visual=$('#budgetVisualText'),dashRing=$('#dashBudgetRing'),dash=$('#dashBudget');if(ring)ring.style.setProperty('--ring',`${pct}%`);if(ringText)ringText.textContent=`${pct}%`;if(visual)visual.textContent=msg;if(dashRing)dashRing.style.setProperty('--meter',`${pct}%`);if(dash)dash.textContent=total?money(rem):'—'}
function saveBudget(){store.set('mcallen.budget',{total:$('#budgetTotal').value,spent:$('#budgetSpent').value});renderBudget()}
$('#budgetTotal').addEventListener('input',saveBudget);$('#budgetSpent').addEventListener('input',saveBudget);$('#resetBudget').addEventListener('click',()=>{store.set('mcallen.budget',{total:'',spent:''});renderBudget();toast('Presupuesto reiniciado')});
function renderChecklist(){const s=store.get('mcallen.checks',{});$('#checklist').innerHTML=defaultChecklist.map((t,i)=>`<label class="checkItem"><input type="checkbox" data-i="${i}" ${s[i]?'checked':''}><span>${t}</span><span></span></label>`).join('');$$('#checklist input').forEach(x=>x.addEventListener('change',()=>{const c=store.get('mcallen.checks',{});c[x.dataset.i]=x.checked;store.set('mcallen.checks',c);renderProgress()}));renderProgress()}
$('#resetChecklist').addEventListener('click',()=>{store.set('mcallen.checks',{});renderChecklist();toast('Checklist reiniciado')});
function renderShopping(){const items=store.get('mcallen.shopping',[]);$('#shoppingList').innerHTML=items.length?items.map((it,i)=>`<div class="shopItem ${it.done?'done':''}" data-i="${i}"><input type="checkbox" ${it.done?'checked':''}><div><div class="itemName">${escapeHtml(it.name)}</div><div class="itemMeta">${escapeHtml(it.store||'Sin tienda')}${it.note?` · ${escapeHtml(it.note)}`:''}${it.price?` · ${money(it.price)}`:''}</div></div><button class="delete" aria-label="Eliminar">×</button></div>`).join(''):'<div class="empty">Todavía no hay encargos. Disfruta estos cinco minutos de paz.</div>';$$('#shoppingList .shopItem').forEach(row=>{row.querySelector('input').addEventListener('change',e=>{const a=store.get('mcallen.shopping',[]);a[row.dataset.i].done=e.target.checked;store.set('mcallen.shopping',a);renderShopping()});row.querySelector('.delete').addEventListener('click',()=>{const a=store.get('mcallen.shopping',[]);a.splice(row.dataset.i,1);store.set('mcallen.shopping',a);renderShopping()})})}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#addShopItem').addEventListener('click',()=>openSheet('itemSheet'));$('#saveItem').addEventListener('click',()=>{const name=$('#itemName').value.trim();if(!name){toast('Escribe el artículo');return}const a=store.get('mcallen.shopping',[]);a.push({name,store:$('#itemStore').value.trim(),price:$('#itemPrice').value,note:$('#itemNote').value.trim(),done:false});store.set('mcallen.shopping',a);['#itemName','#itemStore','#itemPrice','#itemNote'].forEach(s=>$(s).value='');closeSheets();renderShopping();toast('Artículo agregado')});
const notes=$('#notes');notes.value=store.get('mcallen.notes','');notes.addEventListener('input',()=>{store.set('mcallen.notes',notes.value);$('#notesSaved').textContent='Guardado ✓';clearTimeout(state.noteTimer);state.noteTimer=setTimeout(()=>$('#notesSaved').textContent='Guardado automático en este dispositivo.',1200)});
function openSheet(id){$('#'+id).classList.remove('hidden')}function closeSheets(){$$('.sheet').forEach(s=>s.classList.add('hidden'))}$$('[data-close-sheet]').forEach(b=>b.addEventListener('click',closeSheets));$$('.sheet').forEach(s=>s.addEventListener('click',e=>{if(e.target===s)closeSheets()}));
$('#routeSettings').addEventListener('click',()=>{const s=store.get('mcallen.settings',{days:2,pace:'family',hotel:'comfort'});$('#tripDays').value=s.days;$('#tripPace').value=s.pace;$('#tripHotel').value=s.hotel;openSheet('settingsSheet')});$('#saveSettings').addEventListener('click',()=>{const s={days:Number($('#tripDays').value),pace:$('#tripPace').value,hotel:$('#tripHotel').value};store.set('mcallen.settings',s);$('#routeSummary').textContent=`${s.days} día${s.days===1?'':'s'} · ${s.pace==='family'?'ritmo familiar':s.pace==='fast'?'compras intensivas':'ritmo tranquilo'} · ${s.hotel==='home2'?'Home2 Suites':'Comfort Inn Pharr'}.`;closeSheets();renderRoute();toast('Itinerario actualizado')});
