const SEARCH_ENDPOINT='https://nominatim.openstreetmap.org/search';
const SEARCH_ATTRIBUTION='Datos © OpenStreetMap contributors';
function inferCategory(r){const s=`${r.name||''} ${r.type||''} ${r.category||''}`.toLowerCase();if(/pizza|restaurant|fast_food|cafe|food|burger|buffet|taco|bakery/.test(s))return 'Comida';if(/hotel|motel|lodging/.test(s))return 'Hotel';if(/pharmacy|supermarket|convenience|fuel|hospital/.test(s))return 'Esenciales';if(/museum|park|playground|zoo|cinema/.test(s))return 'Niños';return 'Compras'}
function categoryIcon(cat){return ({Comida:'🍕',Hotel:'🏨',Esenciales:'💊',Niños:'🦖',Compras:'🛍️'})[cat]||'📍'}
function normalizeRemote(r){const name=r.namedetails?.name||r.name||r.display_name?.split(',')[0]||'Lugar';const cat=inferCategory({...r,name});return {id:`osm-${r.osm_type||'p'}-${r.osm_id||r.place_id}`,name,cat,icon:categoryIcon(cat),zone:r.address?.suburb||r.address?.city||r.address?.town||'McAllen / RGV',query:r.display_name,address:r.display_name,desc:'Lugar encontrado en OpenStreetMap.',lat:Number(r.lat),lon:Number(r.lon),hours:r.extratags?.opening_hours||'',phone:r.extratags?.phone||r.extratags?.['contact:phone']||'',website:r.extratags?.website||r.extratags?.['contact:website']||'',custom:true,source:'OpenStreetMap'} }
async function searchOnlinePlaces(){const input=$('#placeSearch'),q=input.value.trim();if(q.length<2){toast('Escribe al menos dos letras');return}if(!navigator.onLine){toast('La búsqueda en línea necesita internet');return}const now=Date.now();if(now-state.lastSearchAt<1100){toast('Espera un momento antes de buscar otra vez');return}state.lastSearchAt=now;const key=q.toLowerCase();const cache=store.get('mcallen.searchCache',{});if(cache[key]&&now-cache[key].time<7*24*3600*1000){state.remoteResults=cache[key].items;renderRemoteResults();return}const btn=$('#onlineSearchBtn');btn.disabled=true;btn.textContent='Buscando…';$('#onlineResults').innerHTML='<article class="card empty">Consultando lugares de McAllen y el Valle…</article>';try{const params=new URLSearchParams({format:'jsonv2',q:`${q}, McAllen, Texas`,limit:'8',addressdetails:'1',extratags:'1',namedetails:'1',countrycodes:'us',viewbox:'-98.50,26.45,-97.75,25.95',bounded:'1','accept-language':'es,en'});const res=await fetch(`${SEARCH_ENDPOINT}?${params}`);if(!res.ok)throw new Error(`HTTP ${res.status}`);const raw=await res.json();state.remoteResults=raw.map(normalizeRemote);cache[key]={time:now,items:state.remoteResults};const keys=Object.keys(cache).sort((a,b)=>cache[b].time-cache[a].time).slice(0,20),trim={};keys.forEach(k=>trim[k]=cache[k]);store.set('mcallen.searchCache',trim);renderRemoteResults()}catch(error){$('#onlineResults').innerHTML='<article class="card"><h3>No pude consultar lugares</h3><p>Revisa la conexión e inténtalo de nuevo. También puedes abrir la búsqueda directamente en Google Maps.</p><div class="actions"><a class="btn primary" target="_blank" rel="noopener" href="'+mapUrl(q+' McAllen Texas')+'">Buscar en Maps</a></div></article>'}finally{btn.disabled=false;btn.textContent='Buscar en McAllen'}}
function renderRemoteResults(){const box=$('#onlineResults'),items=state.remoteResults;if(!items.length){box.innerHTML='<article class="card empty">No aparecieron resultados. Prueba un nombre más específico, por ejemplo “Pizza Hut”.</article>';return}box.innerHTML=`<div class="resultHeader"><b>${items.length} resultados en línea</b><small>${SEARCH_ATTRIBUTION} · Los horarios dependen de los datos publicados.</small></div>`+items.map(p=>`<article class="card onlinePlace" data-remote-id="${p.id}"><div class="place"><div class="placeIcon">${p.icon}</div><div><span class="tag">${p.cat}</span><span class="tag gray">${escapeHtml(p.zone)}</span><h3>${escapeHtml(p.name)}</h3><address>${escapeHtml(p.address)}</address><p>${p.hours?`<strong>Horario publicado:</strong> ${escapeHtml(p.hours)}`:'<strong>Horario:</strong> no publicado; verifica en Maps antes de salir.'}</p>${p.phone?`<p>☎ ${escapeHtml(p.phone)}</p>`:''}<div class="actions"><a class="btn primary" href="${mapUrl(p.query)}" target="_blank" rel="noopener">Maps</a><a class="btn" href="${wazeUrl(p.query)}" target="_blank" rel="noopener">Waze</a><button class="btn remoteAdd" data-day="1">＋ Día 1</button><button class="btn remoteAdd" data-day="2">＋ Día 2</button><button class="btn remoteAdd" data-day="3">＋ Día 3</button></div></div></div></article>`).join('');$$('.remoteAdd',box).forEach(b=>b.addEventListener('click',()=>{const card=b.closest('[data-remote-id]'),p=state.remoteResults.find(x=>x.id===card.dataset.remoteId);saveCustomPlace(p);addPlaceToDay(p.id,Number(b.dataset.day))}))}
function saveCustomPlace(place){let list=store.get('mcallen.customPlaces',[]);const i=list.findIndex(p=>p.id===place.id);if(i>=0)list[i]={...list[i],...place,custom:true};else list.push({...place,custom:true});store.set('mcallen.customPlaces',list)}
function addPlaceToDay(id,day){const p=getSpot(id);if(!p){toast('No encontré ese lugar');return}if(p.custom)saveCustomPlace(p);const cr=store.get('mcallen.customRoutes',{});cr[day]=[...new Set([...(cr[day]||[]),id])];store.set('mcallen.customRoutes',cr);toast(`${p.name} agregado al Día ${day}`);if(state.day===day)renderRoute();renderPlaces()}
function deleteCustomPlace(id){let places=store.get('mcallen.customPlaces',[]).filter(p=>p.id!==id);store.set('mcallen.customPlaces',places);const cr=store.get('mcallen.customRoutes',{});Object.keys(cr).forEach(k=>cr[k]=(cr[k]||[]).filter(x=>x!==id));store.set('mcallen.customRoutes',cr);store.set('mcallen.visited',store.get('mcallen.visited',[]).filter(x=>x!==id));renderPlaces();renderRoute();toast('Lugar eliminado')}
$('#onlineSearchBtn').addEventListener('click',searchOnlinePlaces);$('#placeSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchOnlinePlaces()}});
function haversineKm(aLat,aLon,bLat,bLon){const R=6371,toRad=v=>v*Math.PI/180,dLat=toRad(bLat-aLat),dLon=toRad(bLon-aLon),a=Math.sin(dLat/2)**2+Math.cos(toRad(aLat))*Math.cos(toRad(bLat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(a))}
function formatDistance(km){if(!Number.isFinite(km))return '—';return km<1?`${Math.round(km*1000)} m`:`${km.toFixed(km<10?1:0)} km`}
function startGPS(){if(!('geolocation'in navigator)){toast('Este navegador no ofrece ubicación');return}if(state.gpsWatch!==null){navigator.geolocation.clearWatch(state.gpsWatch);state.gpsWatch=null;state.userLocation=null;$('#gpsToggle').textContent='Usar mi ubicación';updateGPSPanel();renderDynamicMap();renderPlaces();return}$('#gpsToggle').textContent='Buscando…';$('#gpsStatus').textContent='El teléfono pedirá permiso. La ubicación no se guarda.';state.gpsWatch=navigator.geolocation.watchPosition(pos=>{state.userLocation={lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy,updatedAt:Date.now()};$('#gpsToggle').textContent='Detener GPS';updateGPSPanel();renderDynamicMap();renderPlaces()},err=>{state.gpsWatch=null;$('#gpsToggle').textContent='Usar mi ubicación';const msg=err.code===1?'Permiso de ubicación rechazado. Actívalo en Safari/Chrome para este sitio.':err.code===2?'No pude determinar la ubicación.':'La ubicación tardó demasiado.';$('#gpsStatus').textContent=msg;toast(msg)},{enableHighAccuracy:true,maximumAge:15000,timeout:20000})}
function nextRouteSpot(){const done=store.get('mcallen.visited',[]);return currentRoute().map(getSpot).find(p=>p&&!done.includes(p.id)&&Number.isFinite(p.lat)&&Number.isFinite(p.lon))}
function updateGPSPanel(){const status=$('#gpsStatus'),next=$('#gpsNext'),nav=$('#navNextStop');if(!state.userLocation){status.textContent='Activa el GPS para ver distancias y la siguiente parada. Tu ubicación no se almacena.';next.innerHTML='<b>Sin ubicación activa</b><small>Disponible en HTTPS con permiso del teléfono.</small>';nav.disabled=true;return}const p=nextRouteSpot();status.textContent=`Ubicación activa · precisión aproximada ${Math.round(state.userLocation.accuracy)} m · no guardada`;if(!p){next.innerHTML='<b>🎉 Día completado</b><small>No quedan paradas pendientes con ubicación.</small>';nav.disabled=true;return}const km=haversineKm(state.userLocation.lat,state.userLocation.lon,p.lat,p.lon);next.innerHTML=`<b>${p.icon||'📍'} Siguiente: ${escapeHtml(p.name)}</b><small>A ${formatDistance(km)} de tu posición actual.</small>`;nav.disabled=false;nav.onclick=()=>open(`https://www.google.com/maps/dir/?api=1&origin=${state.userLocation.lat},${state.userLocation.lon}&destination=${encodeURIComponent(p.query)}&travelmode=driving`,'_blank','noopener')}
$('#gpsToggle').addEventListener('click',startGPS);$('#navNextStop').disabled=true;
function mapPoint(p){if(Array.isArray(p.map))return {x:p.map[0],y:p.map[1]};if(Number.isFinite(p.lat)&&Number.isFinite(p.lon)){const x=25+(p.lon+98.34)/(.42)*335,y=450-(p.lat-26.08)/(.25)*355;return {x:Math.max(25,Math.min(365,x)),y:Math.max(65,Math.min(455,y))}}return null}
function renderDynamicMap(){const group=$('#mapPins');if(!group)return;const ids=currentRoute(),ps=ids.map(getSpot).filter(Boolean).map((p,i)=>({...p,...mapPoint(p),n:i+1})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));const dayTint=state.day===1?'<rect x="18" y="230" width="350" height="180" rx="28" fill="#ffb84d" opacity=".10"/>':state.day===2?'<rect x="18" y="48" width="350" height="190" rx="28" fill="#0aa79e" opacity=".11"/>':'<rect x="270" y="245" width="105" height="140" rx="25" fill="#ef6f62" opacity=".11"/>';const path=ps.length>1?`<polyline class="activeRouteLine" points="${ps.map(p=>`${p.x},${p.y}`).join(' ')}"/>`:'';const pins=ps.map(p=>`<g class="pin routePin" data-id="${p.id}" transform="translate(${p.x} ${p.y})"><circle r="15"/><text y="1">${p.n}</text></g>`).join('');let user='';if(state.userLocation){const up=mapPoint(state.userLocation);if(up)user=`<g class="userPin" transform="translate(${up.x} ${up.y})"><circle r="11"/><circle r="4"/><text x="16" y="4">Tú</text></g>`}group.innerHTML=dayTint+path+pins+user;$$('.routePin',group).forEach(g=>g.addEventListener('click',()=>{const p=getSpot(g.dataset.id);$('#mapInfo').innerHTML=`<b>${p.icon||'📍'} ${escapeHtml(p.name)}</b><p>${escapeHtml(p.desc||p.address||'Parada del itinerario.')}</p>${p.hours?`<p><strong>Horario:</strong> ${escapeHtml(p.hours)}</p>`:''}<div class="actions"><a class="btn primary" href="${mapUrl(p.query)}" target="_blank" rel="noopener">Maps</a><a class="btn" href="${wazeUrl(p.query)}" target="_blank" rel="noopener">Waze</a></div>`}))}
async function renderStorageStatus(){const ok=store.available(),meta=store.get(STORE_META,null),status=$('#storageStatus'),date=$('#lastSavedAt');if(status)status.textContent=ok?'Guardado local activo':'Almacenamiento local bloqueado';if(date)date.textContent=meta?.updatedAt?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(meta.updatedAt)):'Aún no hay cambios guardados';const count=store.get('mcallen.customPlaces',[]).length;if($('#savedPlaceCount'))$('#savedPlaceCount').textContent=`${count} lugar${count===1?'':'es'} agregado${count===1?'':'s'}`;if(navigator.storage?.estimate){try{const e=await navigator.storage.estimate();if($('#storageUsage'))$('#storageUsage').textContent=e.usage?`${Math.max(1,Math.round(e.usage/1024))} KB usados en este origen`:'Uso mínimo'}catch{}}}
async function requestPersistentStorage(){if(!navigator.storage?.persist){toast('Este navegador no ofrece protección adicional');return}try{const granted=await navigator.storage.persist();toast(granted?'El navegador aceptó proteger los datos':'El navegador mantendrá su política normal de almacenamiento');renderStorageStatus()}catch{toast('No pude solicitar protección adicional')}}
$('#protectStorage').addEventListener('click',requestPersistentStorage);window.addEventListener('mcallen:saved',renderStorageStatus);
$('#restoreBackup').addEventListener('click',()=>$('#restoreFile').click());$('#restoreFile').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());importBackup(data);toast('Respaldo restaurado');location.reload()}catch{toast('El archivo no parece un respaldo válido')}finally{e.target.value=''}});
function importBackup(d){if(!d||typeof d!=='object')throw new Error('invalid');const map={settings:'mcallen.settings',shopping:'mcallen.shopping',checks:'mcallen.checks',budget:'mcallen.budget',notes:'mcallen.notes',visited:'mcallen.visited',customPlaces:'mcallen.customPlaces',customRoutes:'mcallen.customRoutes'};Object.entries(map).forEach(([src,dst])=>{if(d[src]!==undefined)store.set(dst,d[src])})}
renderStorageStatus();
