function exportState(){return {version:APP_VERSION,exportedAt:new Date().toISOString(),settings:store.get('mcallen.settings',{days:2,pace:'family',hotel:'comfort'}),shopping:store.get('mcallen.shopping',[]),checks:store.get('mcallen.checks',{}),budget:store.get('mcallen.budget',{total:'',spent:''}),notes:store.get('mcallen.notes',''),visited:store.get('mcallen.visited',[]),customPlaces:store.get('mcallen.customPlaces',[]),customRoutes:store.get('mcallen.customRoutes',{})}}
function encodePlan(data){return btoa(unescape(encodeURIComponent(JSON.stringify(data))))}function decodePlan(s){return JSON.parse(decodeURIComponent(escape(atob(s))))}
function sharedUrl(){const u=new URL(location.href);u.hash='plan='+encodePlan(exportState());return u.toString()}
async function shareUrl(url,text='Guía familiar McAllen Go'){try{if(navigator.share)await navigator.share({title:'McAllen Go',text,url});else{await navigator.clipboard.writeText(url);toast('Enlace copiado')}}catch(e){if(e.name!=='AbortError')toast('No se pudo compartir')}}
$('#shareTop').addEventListener('click',()=>shareUrl(location.href));$('#sharePlan').addEventListener('click',()=>shareUrl(sharedUrl(),'Te comparto nuestro plan de McAllen'));$('#shareAll').addEventListener('click',()=>shareUrl(sharedUrl(),'Te comparto la guía y el plan de McAllen'));$('#copyLink').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(sharedUrl());toast('Enlace con plan copiado')}catch{toast('No se pudo copiar')}});$('#downloadBackup').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(exportState(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mcallen-go-respaldo-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
function checkSharedPlan(){const m=location.hash.match(/^#plan=(.+)$/);if(!m)return;try{state.pendingImport=decodePlan(m[1]);openSheet('importSheet')}catch{location.hash=''}}
$('#importPlan').addEventListener('click',()=>{const d=state.pendingImport;if(!d)return;importBackup(d);notes.value=d.notes||'';history.replaceState(null,'',location.pathname);closeSheets();renderShopping();renderChecklist();renderBudget();renderPlaces();renderRoute();toast('Plan importado')});$('#ignoreImport').addEventListener('click',()=>{history.replaceState(null,'',location.pathname);closeSheets()});
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installText').textContent='Tu dispositivo permite instalarla como app.'});window.addEventListener('appinstalled',()=>{toast('McAllen Go instalada');$('#installCard').classList.add('hidden')});
function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone}
function installFlow(){if(isStandalone()){toast('Ya está instalada');return}const box=$('#installInstructions');if(deferredPrompt){box.innerHTML='<p>Instálala para abrirla a pantalla completa y conservar la guía sin conexión.</p>';$('#triggerInstall').classList.remove('hidden')}else if(isIOS()){box.innerHTML='<p><b>En iPhone:</b></p><ol><li>Ábrela en Safari.</li><li>Toca el botón <b>Compartir</b>.</li><li>Elige <b>Agregar a pantalla de inicio</b>.</li><li>Confirma con <b>Agregar</b>.</li></ol>';$('#triggerInstall').classList.add('hidden')}else{box.innerHTML='<p>Abre el menú del navegador y elige <b>Instalar aplicación</b> o <b>Agregar a pantalla de inicio</b>.</p>';$('#triggerInstall').classList.add('hidden')}openSheet('installSheet')}
['#installTop','#installMain','#installMore'].forEach(s=>$(s).addEventListener('click',installFlow));$('#triggerInstall').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;closeSheets()});
function updateOnline(){const off=!navigator.onLine;$('#offlineBanner').classList.toggle('hidden',!off)}window.addEventListener('online',updateOnline);window.addEventListener('offline',updateOnline);updateOnline();
$$('[data-family]').forEach(b=>b.addEventListener('click',()=>{const kind=b.dataset.family;state.category=kind==='food'?'Comida':kind==='kids'?'Niños':'Esenciales';showScreen('places');$$('#placeFilters .chip').forEach(x=>x.classList.toggle('active',x.dataset.cat===state.category));renderPlaces()}));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderBridges();renderRoute();renderPlaces();renderShopping();renderChecklist();renderBudget();renderProgress();renderStorageStatus();checkSharedPlan();
